### ISSUE TITLE
Limit stdout/stderr output to only stuff the server renders

### ISSUE THREAD

**Issue by hassox** [mjackson/react-stdio#1]
When rendering the component, if there is any console.log or process.stdout calls in the script that react-stdio is running, this will pollute the STDOUT stream and cause invalid JSON to be put out.

**Comment by mjackson** [comment]
Ya, hmmmm... good call. I'll fix this.

**Comment by hassox** [comment]
Thanks!

**Comment by mjackson** [comment]
Released in v2.0.7

**Comment by hassox** [comment]
fast!
