### ISSUE TITLE
Implicit babel-register

### ISSUE THREAD

**Issue by igl** [mjackson/react-stdio#6]
[Here](https://github.com/mjackson/react-stdio/blob/master/server.js#L99-L102).

I already do a WP build for the server bundle with additional babel plugins and [babel-preset-node5](https://www.npmjs.com/package/babel-preset-node5) instead of `es2015`.

Would you mind if this is removed or are interested in a PR making it optional via flags?
Thinking: `--babel-presets node5 react` `--babel-plugins transform-export-extensions`

**Comment by tristanoneil** [comment]
:+1: Just had to fork to add support for the `stage-0` preset. Seems like it'd be best if the server supported configuration from `.bowerc`.

**Comment by igl** [comment]
I vote for simply dropping babel-register. You can transpile or put those 3 lines in your own app entry file if needed.

**Comment by tristanoneil** [comment]
@igl Ah yea that'd be fine too. Ended up moving `babel-register` to the main entry point.

**Comment by tristanoneil** [comment]
@igl How are you passing a bundle to react-stdio? It seems to me that the bundle can only include a single component then. Am I incorrect in this assumption? The README says

> you should create your bundle first and tell react-stdio to load your bundle instead of the plain component file.

but seems a bit vague.

**Comment by igl** [comment]
Yea. I use webpack with:

    output : {
        libraryTarget: "commonjs2"
    }


My Entry file returns a redux/react-router app. I don't do the sub-routing in elixir.

    export default function App (props) {
        return (
            <Provider store={ store }>
                <Router ...

**Comment by mjackson** [comment]
@tristanoneil If you'd like to do your own code transformations you'll need to create a separate bundle for each component you'd like to render, and set that component as the bundle's default export.

@igl Is the babel-register call messing with your app? Seems like if you're building your own bundle it's a no-op.

**Comment by mjackson** [comment]
Fixed in #7
